Add BindingSLCoreService
SonarSource/sonarlint-visualstudio pull request #5168
Opened 2024-01-05 14:40 UTC by ugras-ergun-sonarsource

Fixes #5167

2024-01-16 12:39 UTC, georgii-borovinskikh-sonarsource requested changes

2024-01-16 12:39 UTC, georgii-borovinskikh-sonarsource commented on src/SLCore/Service/Project/IBindingSLCoreService.cs
> +    public interface IBindingSLCoreService
Same notes as other PRs in the chain

2024-01-24 15:33 UTC, ugras-ergun-sonarsource commented on src/SLCore/Service/Project/IConfigurationScopeSLCoreService.cs
> +        /// <param name="parameters"></param>
realised that forgot to update doc comments in previous pr

2024-01-25 09:48 UTC, georgii-borovinskikh-sonarsource approved these changes

2024-01-25 10:10 UTC, merged