SLVS-1576   Update product name in marketplace
SonarSource/sonarlint-visualstudio pull request #5809
Opened 2024-11-07 13:52 UTC by gabriela-trutan-sonarsource

2024-11-11 16:03 UTC, farah22 requested changes
On line 11 there is one mention of SonarQube for Visual Studio, if you could change it to SonarQube for IDE: Visual Studio. the rest is fine

2024-11-11 16:15 UTC, gabriela-trutan-sonarsource commented on MarketPlaceFiles/VS2022/overview-2022.md
> +SonarQube for IDE helps you detect and fix Bugs, Code Smells, and Security Vulnerabilities in-IDE.
From Farah: 

```suggestion
SonarQube for IDE (formerly SonarLint) helps you detect and fix Bugs, Code Smells, and Security Vulnerabilities in-IDE. 
```

2024-11-12 08:12 UTC, vnaskos-sonar approved these changes
👍

2024-11-12 09:56 UTC, farah22 approved these changes

2024-11-12 10:29 UTC, merged