Gb/taint synchronizer
SonarSource/sonarlint-visualstudio pull request #5821
Opened 2024-11-11 14:06 UTC by georgii-borovinskikh-sonarsource

Part of

2024-11-13 15:12 UTC, gabriela-trutan-sonarsource requested changes
Functionality works, but:

- You missed a todo that was supposed to be done in this task in [TaintVulnerabilityListener](https://github.com/SonarSource/sonarlint-visualstudio/blob/e64f8fdea71591678fefa90e6614756274e528c4/src/SLCore.Listeners/Implementation/TaintVulnerabilityListener.cs#L41)
- I have some more feedback

2024-11-13 15:49 UTC, georgii-borovinskikh-sonarsource commented on src/IssueViz.Security/Taint/TaintStore.cs
> -        public AnalysisInformation GetAnalysisInformation() => analysisInformation;
I will fix it in the SSE PR, as the method set is going to change there

2024-11-13 15:50 UTC, georgii-borovinskikh-sonarsource commented on src/IssueViz.Security/Taint/TaintStore.cs
>                  var indexToRemove =
1) This method is removed in SSE PR 2) it is better technically. Remove by index is faster than by value

2024-11-13 15:51 UTC, georgii-borovinskikh-sonarsource commented on src/IssueViz.Security/Taint/TaintIssuesSynchronizer.cs
> +            logger.LogVerbose("Configuration scope root hasn't been initialized.");
IMO it's not required for verbose logs

2024-11-13 15:52 UTC, georgii-borovinskikh-sonarsource commented on src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
> +            AnalysisInformation = new AnalysisInformation("stub", DateTimeOffset.Now);
https://github.com/SonarSource/sonarlint-visualstudio/pull/5829

2024-11-13 15:54 UTC, georgii-borovinskikh-sonarsource commented on src/IssueViz.Security/Taint/TaintIssuesConfigurationScopeMonitor.cs
> +            this.activeConfigScopeTracker.CurrentConfigurationScopeChanged += ActiveConfigScopeTrackerOnCurrentConfigurationScopeChanged;
Separable responsibility, can be (and already was) in a different class

2024-11-13 15:55 UTC, gabriela-trutan-sonarsource commented on src/IssueViz.Security/Taint/TaintStore.cs
> -        public AnalysisInformation GetAnalysisInformation() => analysisInformation;
Can you maybe write it in the corresponding task, so we won't forget?

2024-11-13 15:56 UTC, gabriela-trutan-sonarsource commented on src/IssueViz.Security/Taint/TaintIssuesSynchronizer.cs
> +            logger.LogVerbose("Configuration scope root hasn't been initialized.");
For consistency reasons, I think we should do it.

2024-11-13 15:57 UTC, gabriela-trutan-sonarsource commented on src/IssueViz.Security/Taint/TaintIssuesConfigurationScopeMonitor.cs
> +            this.activeConfigScopeTracker.CurrentConfigurationScopeChanged += ActiveConfigScopeTrackerOnCurrentConfigurationScopeChanged;
I know it already has. But does it make sense to have just a class with an event subscription, that delegates the work to the synchronizer?
The responsibility of the synchronizer is to synchronize! So it should know when to do that as well (like subscribing to the corresponding events)

2024-11-13 16:16 UTC, gabriela-trutan-sonarsource commented on src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
> +            AnalysisInformation = new AnalysisInformation("stub", DateTimeOffset.Now);
I see. Maybe next time add a todo with a link to the task/PR? :)

2024-11-14 09:21 UTC, georgii-borovinskikh-sonarsource commented on src/IssueViz.Security/Taint/TaintStore.cs
> +        string ConfigurationScope { get; }
Discussed. Keeping this to be used in SSE implementation PR to discard events for sse events that happen out of order

2024-11-14 10:36 UTC, gabriela-trutan-sonarsource approved these changes

2024-11-14 10:37 UTC, merged